= Create

`Create` is a utility to create in-memory collections (as <<Values, Values>> or <<TimestampedValues, TimestampedValues>> root PTransforms that produce the values when executed).

Create utility is especially useful during testing.

== [[empty]] empty Utility

[source,java]
----
Values<T> empty(
  Coder<T> coder)
Values<Row> empty(
  Schema schema)
Values<T> empty(
  TypeDescriptor<T> type)
----

empty creates an empty <<Values, Values>> root PTransform.

== [[of]] of Utility

[source,java]
----
Values<T> of(
  Iterable<T> elems)
Values<KV<K, V>> of(
  Map<K, V> elems)
Values<T> of(
  T elem,
  T... elems)
----

of creates a <<Values, Values>> root PTransform with the elements given.

== [[ofProvider]] ofProvider Utility

[source,java]
----
OfValueProvider<T> ofProvider(
  ValueProvider<T> provider,
  Coder<T> coder)
----

== [[timestamped]] timestamped Utility

[source,java]
----
TimestampedValues<T> timestamped(
  Iterable<T> values,
  Iterable<Long> timestamps)
TimestampedValues<T> timestamped(
  Iterable<TimestampedValue<T>> elems)
TimestampedValues<T> timestamped(
  TimestampedValue<T> elem,
  TimestampedValue<T>... elems)
----

timestamped creates a <<TimestampedValues, TimestampedValues>> with the elements given.

== [[demo]] Demo

[source,plaintext]
----
import org.apache.beam.sdk.Pipeline
val p = Pipeline.create()

import org.apache.beam.sdk.transforms.Create
val nums = Create.of(0, 1, 2, 3, 4, 5)

scala> :type nums
org.apache.beam.sdk.transforms.Create.Values[Int]

p.apply("Input Numbers", nums)
----

== [[Values]] Values Root PTransform

`Values<T>` is a xref:PTransform.adoc#root[root PTransform] that produces a xref:PCollection.adoc[] from a set of in-memory objects (of type `T`).

[source,java]
----
PTransform<PBegin, PCollection<T>>
----

Values takes the following to be created:

* [[elems]] Elements (`Iterable<T>`)
* [[coder]] Optional xref:coders:Coder.adoc[] (`Optional<Coder<T>>`)
* [[typeDescriptor]] Optional TypeDescriptor (`Optional<TypeDescriptor<T>>`)

Values is created using xref:Create.adoc#of[Create.of] and xref:Create.adoc#empty[Create.empty] utilities.

Values is a static class of xref:Create.adoc[] utility.

== [[TimestampedValues]] TimestampedValues Root PTransform

`TimestampedValues<T>` is...FIXME
