= PipelineRunnerRegistrar

`PipelineRunnerRegistrar` is a way for Beam developers to extend the Beam framework with a new xref:PipelineRunner.adoc[].

PipelineRunnerRegistrar uses {java-javadoc-url}/java.base/java/util/ServiceLoader.html[java.util.ServiceLoader] utility (with a corresponding `META-INF/services` directory).

Apache Beam recommends using https://github.com/google/auto/tree/master/service[@AutoService] annotation to generate the necessary META-INF files automatically at build time.

== [[register]] Cache.register

[source,java]
----
void register(
  Class<? extends PipelineOptions> iface)
----

`register` is used to register a new xref:PipelineOptions.adoc[].

`register` is used when:

* PipelineOptionsFactory is requested to xref:PipelineOptionsFactory.adoc#register[register]

* Cache (of PipelineOptionsFactory) is requested to <<initializeRegistry, initializeRegistry>>

== [[initializeRegistry]] Cache.initializeRegistry

[source,java]
----
void initializeRegistry(
  ClassLoader loader)
----

`initializeRegistry` finds all xref:PipelineOptionsRegistrar.adoc[PipelineOptionsRegistrars] (in the given ClassLoader) and requests them for xref:PipelineOptionsRegistrar.adoc#getPipelineOptions[PipelineOptions].

`initializeRegistry` is used when the Cache is created (that happens in a static initialization block of xref:PipelineOptionsFactory.adoc[] when requested to <<resetCache, resetCache>>).

== [[resetCache]] Cache.resetCache

`resetCache` resets the factory to the default state. That triggers searching the application's classloader for [PipelineRunnerRegistrars](#PipelineRunnerRegistrar) (using [ReflectHelpers.loadServicesOrdered](#ReflectHelpers)). The PipelineRunnerRegistrars are requested for [PipelineRunners](#PipelineRunner). The PipelineRunners are requested for [PipelineOptions](#PipelineOptions).

With that, [PipelineRunners](#PipelineRunner) and [PipelineOptions](#PipelineOptions) are all registered with the [PipelineOptionsFactory](#PipelineOptionsFactory).

== [[loadServicesOrdered]] ReflectHelpers.loadServicesOrdered

`loadServicesOrdered` is used to discover PipelineRunnerRegistrars and xref:PipelineOptionsRegistrar.adoc[PipelineOptionsRegistrars].
