= Pipeline

`Pipeline` is a *directed acyclic graph* (https://en.wikipedia.org/wiki/Directed_acyclic_graph[DAG]) of xref::PTransform.adoc[]s and xref::PCollection.adoc[]s.

Pipeline can be run using a xref::PipelineRunner.adoc[].

== [[create]] Creating Pipeline

[source,java]
----
Pipeline create() // <1>
Pipeline create(
  PipelineOptions options)
----
<1> Uses PipelineOptionsFactory to xref:PipelineOptionsFactory.adoc#create[create a PipelineOptions]

`Pipeline.create` utility creates a new Pipeline (using the provided xref:PipelineOptions.adoc[] or requests xref:PipelineOptionsFactory.adoc[] to xref:PipelineOptionsFactory.adoc#create[create one]).

create prints out the following DEBUG message to the logs:

[source,plaintext]
----
Creating [pipeline]
----

== [[run]] Running Pipeline

[source,java]
----
PipelineResult run() // <1>
PipelineResult run(
  PipelineOptions options)
----
<1> Uses the <<defaultOptions, default options>>

run creates a xref:PipelineRunner.adoc[] (using xref:PipelineRunner.adoc#fromOptions[PipelineRunner.fromOptions]).

run prints out the following DEBUG message to the logs:

[source,plaintext]
----
Running [this] via [runner]
----

run <<validate, validates the options>> and requests the PipelineRunner to xref:PipelineRunner.adoc#run[run this pipeline].

== [[validate]] Validating Pipeline Options

[source,java]
----
void validate(
  PipelineOptions options)
----

validate...FIXME

== [[creating-instance]] Creating Instance

Pipeline takes the following to be created:

* [[transforms]] xref:TransformHierarchy.adoc[]
* [[options]][[defaultOptions]] xref:PipelineOptions.adoc[]

Pipeline cannot be created directly and can only be created using <<create, Pipeline.create>> utility.

== [[applyTransform]] applyTransform Utility

[source,java]
----
<
  InputT extends PInput,
  OutputT extends POutput>
OutputT applyTransform(
  InputT input,
  PTransform<? super InputT, OutputT> transform) // <1>
<
  InputT extends PInput,
  OutputT extends POutput>
OutputT applyTransform(
  String name,
  InputT input,
  PTransform<? super InputT, OutputT> transform)
----
<1> Uses the xref:PTransform.adoc#name[name] of the PTransform

applyTransform...FIXME

applyTransform is used when Pipeline is requested to <<applyTransform, applyTransform>>.

== [[applyInternal]] applyInternal Method

[source,java]
----
<
  InputT extends PInput,
  OutputT extends POutput>
OutputT applyInternal(
  String name,
  InputT input,
  PTransform<? super InputT, OutputT> transform)
----

applyInternal...FIXME

applyInternal is used when Pipeline is requested to <<applyTransform, applyTransform>>.

== [[applyReplacement]] applyReplacement Method

[source,java]
----
<
  InputT extends PInput,
  OutputT extends POutput,
  TransformT extends PTransform<? super InputT, OutputT>>
void applyReplacement(
  Node original,
  PTransformOverrideFactory<InputT, OutputT, TransformT> replacementFactory)
----

applyReplacement...FIXME
