= PipelineRunner

[[ResultT]]
`PipelineRunner<ResultT extends PipelineResult>` is an <<contract, abstraction>> to <<run, run a Pipeline>> (and produce a xref:PipelineResult.adoc[]).

PipelineRunner is defined using xref::PipelineOptions.adoc[].

[source,plaintext]
----
val result = pipeline.run

assert(result.isInstanceOf[org.apache.beam.sdk.PipelineResult])

result.waitUntilFinish
----

[source,plaintext]
----
import org.apache.beam.sdk.options.PipelineOptionsFactory
val options = PipelineOptionsFactory.create()

import org.apache.beam.sdk.PipelineRunner
val runner = PipelineRunner.fromOptions(options)

scala> :type runner
org.apache.beam.sdk.PipelineRunner[_ <: org.apache.beam.sdk.PipelineResult]
----

== [[implementations]] Available PipelineRunners

[cols="40,60",options="header",width="100%"]
|===
| PipelineRunner
| Description

| xref:runners:dataflow/DataflowRunner.adoc[]
| [[DataflowRunner]]

| xref:runners:direct/DirectRunner.adoc[]
| [[DirectRunner]]

| FlinkRunner
| [[FlinkRunner]]

| PortableRunner
| [[PortableRunner]]

| SparkRunnerDebugger
| [[SparkRunnerDebugger]]

| xref:runners:spark/SparkStructuredStreamingRunner.adoc[]
| [[SparkStructuredStreamingRunner]]

| TestSparkRunner
| [[TestSparkRunner]]

|===

NOTE: You can find more runners in the https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/PipelineRunner.html[official documentation].

== [[contract]] Contract

=== [[run]] run Method

[source,java]
----
// ResultT extends PipelineResult
ResultT run(
  Pipeline pipeline)
----

run runs the given xref:Pipeline.adoc[] and produces a xref:PipelineResult.adoc[] (as a <<ResultT, ResultT>>)

Used when Pipeline is requested to xref:Pipeline.adoc#run[run].
