= PTransform

[[In]]
`PTransform[In, Out]` is an *operation* (*function*) with an input of type `In` and an output of type `Out`.

[source,plaintext]
----
PTransform: In => Out
----

A directed acyclic graph of PTransforms and PCollections is a xref::Pipeline.adoc[].

== [[source]][[root]] Root PTransform

*Root PTransform* (_Source PTransform_) is a PTransform that takes no input (conventionally marked as xref:PBegin.adoc[] input type) and produces a xref:PCollection.adoc[] (of values of type `T`).

[source,java]
----
PTransform<PBegin, PCollection<T>>
----

Available root PTransforms: xref:AvroIO.adoc#read[AvroIO.Read], xref:TextIO.adoc#read[TextIO.Read], xref:Create.adoc[].

== [[sink]][[output]] Output PTransform

*Output PTransform* (_Sink PTransform_) is a PTransform that has no output (conventionally marked as xref:PDone.adoc[] output type).

[source,java]
----
PTransform<PCollection<T>, PDone>
----

Available output PTransforms: xref:AvroIO.adoc#write[AvroIO.Write], xref:TextIO.adoc#write[TextIO.Write].
