= PTransform

[[OutputT]][[InputT]]
`PTransform<PInput, POutput>` is an <<contract, abstraction>> of *transformations* (_operations_ or simply _functions_) with xref:PInput.adoc[] input and xref:POutput.adoc[] output.

[source,plaintext]
----
PTransform: PInput => POutput
----

== [[creating-instance]][[name]] Creating Instance

PTransform takes an optional name to be created.

PTransform is an abstract class and cannot be created directly. It is created indirectly for the <<implementations, concrete PTransforms>>.

== [[contract]] Contract

=== [[expand]] expand Method

[source,java]
----
OutputT expand(
  InputT input)
----

Used when Pipeline is requested to xref:Pipeline.adoc#applyInternal[applyInternal] and xref:Pipeline.adoc#applyReplacement[applyReplacement].

== [[implementations]] Subset of Available PTransforms

.PTransforms (Direct Implementations and Extensions Only)
[cols="30,70",options="header",width="100%"]
|===
| PTransform
| Description

| xref:GroupByKey.adoc[]
| [[GroupByKey]]

| xref:MapElements.adoc[]
| [[MapElements]]

| xref:ParDo.adoc#SingleOutput[ParDo.SingleOutput]
| [[SingleOutput]]

| _others_
|

|===

== [[source]][[root]] Root PTransform

*Root PTransform* (_Source PTransform_) is a PTransform that takes no input (conventionally marked as xref:PBegin.adoc[] input type) and produces a xref:PCollection.adoc[] (of values of type `T`).

[source,java]
----
PTransform<PBegin, PCollection<T>>
----

Examples of root PTransforms: xref:AvroIO.adoc#read[AvroIO.Read], xref:TextIO.adoc#read[TextIO.Read], xref:Create.adoc[], xref:KafkaIO.adoc#read[KafkaIO.Read].

== [[sink]][[output]] Output PTransform

*Output PTransform* (_Sink PTransform_) is a PTransform that has no output (conventionally marked as xref:PDone.adoc[] output type).

[source,java]
----
PTransform<PCollection<T>, PDone>
----

Examples of output PTransforms: xref:AvroIO.adoc#write[AvroIO.Write], xref:TextIO.adoc#write[TextIO.Write], xref:KafkaIO.adoc#write[KafkaIO.Write].
